"""Add cascade delete to user relationships

Revision ID: 1d855988a498
Revises: c8d3d6e1728f
Create Date: 2026-03-01 17:59:19.700471
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1d855988a498'
down_revision: Union[str, None] = 'c8d3d6e1728f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
